# Generated by Django 5.1.2 on 2025-01-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('Appointmentdate', models.CharField(max_length=100)),
                ('Reasonforappointment', models.CharField(max_length=100)),
            ],
        ),
    ]
